config/routes.rb
Rails.application.routes.draw do
  resources :clientes

  resources :menus

  resources :usuarios

  root 'application#hello'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
  	render text: "Hola Mundo"
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente ha sido creado.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente ha sido actualizado.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:codigo_dni, :nombre, :apellido, :fecha_naci, :direccion, :distrito, :clave, :delivery, :telefono, :email)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu ha sido creado.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu ha sido actualizado.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:codigo, :nombre_menu, :tipo_menu)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario ha sido creado.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario ha sido modificado ó actualizado.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario ha sido eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombres, :dni, :email, :clave, :tipo, :local)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Código %><br>
    <%= f.text_field :codigo_dni %>
  </div>
  <div class="field">
    <%= f.label :Nombres %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :Apellidos %><br>
    <%= f.text_field :apellido, :cols =>60 %>
  </div>
  <div class="field">
    <%= f.label :Fecha_de_Nacimiento %><br>
    <%= f.date_select :fecha_naci, start_year:1940, last_year:2015 %>
  </div>
  <div class="field">
    <%= f.label :Dirección %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :Distrito %><br>
    <%= f.text_field :distrito %>
  </div>
  <div class="field">
    <%= f.label :Clave %><br>
    <%= f.text_field :clave %>
  </div>
  <div class="field">
    <%= f.label :Dirección_de_Delivery %><br>
    <%= f.text_field :delivery %>
  </div>
  <div class="field">
    <%= f.label :Teléfono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Modificar Cliente</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @cliente %> |
<%= link_to 'Regresar', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Codigo dni</th>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Fecha Nacimiento</th>
      <th>Dirección</th>
      <th>Distrito</th>
<!--      <th>Clave</th> -->
      <th>Delivery</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.codigo_dni %></td>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellido %></td>
        <td><%= cliente.fecha_naci %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.distrito %></td>
<!--    <td><%= cliente.clave %></td> -->
        <td><%= cliente.delivery %></td>
        <td><%= cliente.telefono %></td>
        <td><%= link_to 'Visualizar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Estas Seguro que desea Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Nuevos Clientes</h1>

<%= render 'form' %>

<%= link_to 'Regresar', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo (DNI):</strong>
  <%= @cliente.codigo_dni %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @cliente.apellido %>
</p>

<p>
  <strong>Fecha Nacimiento:</strong>
  <%= @cliente.fecha_naci %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @cliente.direccion %>
</p>

<p>
  <strong>Distrito:</strong>
  <%= @cliente.distrito %>
</p>

<p>
  <strong>Clave:</strong>
  <%= @cliente.clave %>
</p>

<p>
  <strong>Dirección de Delivery:</strong>
  <%= @cliente.delivery %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<%= link_to 'Editar', edit_cliente_path(@cliente) %> |
<%= link_to 'Regresar', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SistMenus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Código %><br>
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :Nombre_de_Menú %><br>
    <%= f.text_field :nombre_menu %>
  </div>
  <div class="field">
    <%= f.label :Tipo_de_Menu %><br>
    <%= f.text_field :tipo_menu %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @menu %> |
<%= link_to 'Regresar', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listido de Menú</h1>

<table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Nombre de Menú</th>
      <th>Tipo de Menú</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.codigo %></td>
        <td><%= menu.nombre_menu %></td>
        <td><%= menu.tipo_menu %></td>
        <td><%= link_to 'Visualizar', menu %></td>
        <td><%= link_to 'Editar', edit_menu_path(menu) %></td>
        <td><%= link_to 'Eliminar', menu, method: :delete, data: { confirm: 'Estas Seguro que deseas Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form' %>

<%= link_to 'Regresar', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Código:</strong>
  <%= @menu.codigo %>
</p>

<p>
  <strong>Nombre de Menú:</strong>
  <%= @menu.nombre_menu %>
</p>

<p>
  <strong>Tipo de Menú:</strong>
  <%= @menu.tipo_menu %>
</p>

<%= link_to 'Editar', edit_menu_path(@menu) %> |
<%= link_to 'Regresar', menus_path %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombres %><br>
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :dni %><br>
    <%= f.text_field :dni %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :clave %><br>
    <%= f.text_field :clave %>
  </div>
    <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
    <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Modificar Usuario</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @usuario %> |
<%= link_to 'Regresar', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Usuarios / Administrador de Local</h1>

<table>
  <thead>
    <tr>
      <th>Nombres y Apellidos</th>
      <th>DNI</th>
      <th>Email</th>
      <th>Tipo</th>
      <th>Local</th>
<!--      <th>Clave</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombres %></td>
        <td><%= usuario.dni %></td>
        <td><%= usuario.email %></td>
<!--        <td><%= usuario.clave %></td> -->
        <td><%= usuario.tipo %></td>
        <td><%= usuario.local %></td>
        <td><%= link_to 'Visualizar', usuario %></td>
        <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: 'Estas Seguro que desea Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Nuevos Usuarios</h1>

<%= render 'form' %>

<%= link_to 'Regresar', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres y Apellidos:</strong>
  <%= @usuario.nombres %>
</p>

<p>
  <strong>DNI:</strong>
  <%= @usuario.dni %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Clave:</strong>
  <%= @usuario.clave %>
</p>

<p>
	<strong>Tipo:</strong>
	<%= @usuario.tipo %>
</p>

<p>
	<strong>Local:</strong>
	<%= @usuario.local %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Regresar', usuarios_path %>